### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by ceb8** [lcgordon/hubble_contours#1]
*Set-up things*
- [X] run cookiecutter
- [x] fix cookiecutter things? organizing? 

*code things* 
- [x] convert to a class object
- [x] add fits file saving (not just PNGs)

*testing things*
- [x] does it work
- [x] tutorial on use

**Comment by ceb8** [comment]
I just copied over what was in the to do list markdown file because it seems like it might be useful as an issue.
